@@ -0,0 +1,158 @@
-- MySQL Script generated by MySQL Workbench
-- Tue May 24 22:40:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema r17DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema r17DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `r17DB` DEFAULT CHARACTER SET utf8 ;
CREATE USER 'R17user'@'localhost' IDENTIFIED BY 'R17';

USE `r17DB` ;
UNINSTALL COMPONENT 'file://component_validate_password';
GRANT ALL ON `r17DB`.* TO 'R17user'@'localhost';

-- -----------------------------------------------------
-- Table `r17DB`.`Authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `r17DB`.`Authors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Firstname` VARCHAR(70) NULL,
  `Lastname` VARCHAR(70) NULL,
  `mail` VARCHAR(70) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r17DB`.`Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `r17DB`.`Articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(70) NULL,
  `content` LONGTEXT NULL,
  `summary` LONGTEXT NULL,
  `Authors_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Articles_Authors1`
    FOREIGN KEY (`Authors_id`)
    REFERENCES `r17DB`.`Authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Articles_Authors1_idx` ON `r17DB`.`Articles` (`Authors_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `r17DB`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `r17DB`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r17DB`.`Articles_Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `r17DB`.`Articles_Categories` (
  `Articles_id` INT NOT NULL,
  `Categories_id` INT NOT NULL,
  PRIMARY KEY (`Articles_id`, `Categories_id`),
  CONSTRAINT `fk_Articles_has_Categories_Articles`
    FOREIGN KEY (`Articles_id`)
    REFERENCES `r17DB`.`Articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_has_Categories_Categories1`
    FOREIGN KEY (`Categories_id`)
    REFERENCES `r17DB`.`Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Articles_has_Categories_Categories1_idx` ON `r17DB`.`Articles_Categories` (`Categories_id` ASC) VISIBLE;

CREATE INDEX `fk_Articles_has_Categories_Articles_idx` ON `r17DB`.`Articles_Categories` (`Articles_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `r17DB`.`Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `r17DB`.`Tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `word` VARCHAR(70) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r17DB`.`Articles_Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `r17DB`.`Articles_Tags` (
  `Articles_id` INT NOT NULL,
  `Tags_id` INT NOT NULL,
  PRIMARY KEY (`Articles_id`, `Tags_id`),
  CONSTRAINT `fk_Articles_has_Tags_Articles1`
    FOREIGN KEY (`Articles_id`)
    REFERENCES `r17DB`.`Articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_has_Tags_Tags1`
    FOREIGN KEY (`Tags_id`)
    REFERENCES `r17DB`.`Tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Articles_has_Tags_Tags1_idx` ON `r17DB`.`Articles_Tags` (`Tags_id` ASC) VISIBLE;

CREATE INDEX `fk_Articles_has_Tags_Articles1_idx` ON `r17DB`.`Articles_Tags` (`Articles_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `r17DB`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `r17DB`.`Comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(70) NULL,
  `likes` INT NULL,
  `mail` VARCHAR(70) NULL,
  `content` LONGTEXT NULL,
  `Articles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Comments_Articles1`
    FOREIGN KEY (`Articles_id`)
    REFERENCES `r17DB`.`Articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Comments_Articles1_idx` ON `r17DB`.`Comments` (`Articles_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `r17DB`.`AdmUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `r17DB`.`AdmUsers` (
  `id` INT NOT NULL,
  `login` VARCHAR(70) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
